name: Daily News Automation
on:
  schedule:
    - cron: '0 10 * * *' # 每天 UTC 时间 00:00 执行（北京时间 8:00）
  workflow_dispatch: # 允许手动触发测试

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Claude
        run: npm install -g @anthropic-ai/claude-code

      - name: Install uvx
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
             curl -LsSf https://astral.sh/uv/install.sh | sh
             claude mcp add -s user MiniMax --env MINIMAX_API_KEY=$ANTHROPIC_API_KEY --env MINIMAX_API_HOST=https://api.minimaxi.com -- uvx minimax-coding-plan-mcp -y


      - name: Run Claude Summary
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_BASE_URL: ${{ vars.ANTHROPIC_BASE_URL }}
          NEWS_PROMPT: ${{ vars.NEWS_PROMPT }}
        run: |
          claude --dangerously-skip-permissions  -p "$NEWS_PROMPT"
      # 安装 Pandoc
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # 转换 Markdown 为 HTML
      # --standalone 生成包含 <body> 的完整文档
      # --self-contained 将样式嵌入 HTML
      - name: Convert to HTML
        env: 
          NEWS_FILE: ${{ vars.NEWS_FILE }}
        run: |
          pandoc $NEWS_FILE \
            --standalone \
            --template=default.html4 \
            -o output.html
      

      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub每日新闻报告"
          to: yahan@iscas.ac.cn
          from: News Reporter
          html_body: file://output.html
